#!/bin/sh
#
# Copyright (C) 2001,2003 Matt Newville <newville@cars.uchicago.edu>
#  
# Purpose:  rerun autoconf and automake after playing with
#           configure.in and other primitive build instruction 
#           files.
# This requires a full set of autotools to be installed, and only
# needs to be run for development, not for building and installation.
#
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#
rm -f config.cache acconfig.h config.h

aclocal #  don't run this, as it blows away the TERMCAP_LIB check
autoconf
autoheader
# acconfig
# automake -a
echo " ready for configure"
exit
