* Xray-XDI version 0.01

This module provides a perl interface to ~libxdifile~, the C interface
to the XDI file format.

** INSTALLATION

Before installation, you must somehow install perl's [[https://metacpan.org/release/Inline][Inline]] package.
This can be installed from the ~cpan~ utility (=install Inline=) or
using your system's package manager (~libinline-perl~ on debian & ubuntu,
~perl-Inline~ on redhat, mandriva, & SUSE).

To install this module type the following:

:   perl Makefile.PL
:   make
:   make test
:   make install

If any tests fail, send a bug report to Bruce Ravel (bravel AT bnl DOT
gov).  The bug report should identify the operating system, the
version of perl (~perl -v~), and screen output from the ~make test~
phase.

For documentation, once installed:

:   perldoc Xray::XDI

** DEPENDENCIES

This module requires these modules, all available from cpan and as
packages for major linux distributions:

 1. Inline
 2. Inline::C
 3. Moose
 4. MooseX::NonMoose
 5. MooseX::Aliases
  

** COPYRIGHT AND LICENCE

To the extent possible, the authors have waived all rights granted by
copyright law and related laws for the code and documentation that
make up the Perl Interface to the XAS Data Interchange Format.  While
information about Authorship may be retained in some files for
historical reasons, this work is hereby placed in the Public Domain.
This work is published from: United States.

Author: Bruce Ravel (bravel AT bnl DOT gov).
Last update: 22 July, 2014
